version: "3.8"

services:
  orchestrator:
    build:
      context: ./orchestrator
    command: python3 ./src/main.py
    environment:
      - API_PORT=80
      - GRPC_PORT=443
    ports:
      - 80:80
      - 443:443
