version: "3.8"

services:
  instance:
    build:
      context: ./instance
    command: python3 ./src/main.py
    environment:
      - API_PORT=80
      - GRPC_PORT=443
    env_file: .env
    ports:
      - 80:80
      - 443:443
