# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: register.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eregister.proto\"\x18\n\nInstanceId\x12\n\n\x02id\x18\x01 \x01(\t\"#\n\x10RegisterResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"%\n\x12UnregisterResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2q\n\x0fRegisterService\x12,\n\x08Register\x12\x0b.InstanceId\x1a\x11.RegisterResponse\"\x00\x12\x30\n\nUnregister\x12\x0b.InstanceId\x1a\x13.UnregisterResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'register_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INSTANCEID._serialized_start=18
  _INSTANCEID._serialized_end=42
  _REGISTERRESPONSE._serialized_start=44
  _REGISTERRESPONSE._serialized_end=79
  _UNREGISTERRESPONSE._serialized_start=81
  _UNREGISTERRESPONSE._serialized_end=118
  _REGISTERSERVICE._serialized_start=120
  _REGISTERSERVICE._serialized_end=233
# @@protoc_insertion_point(module_scope)
